---
- name: deploy to tomcat
  hosts: webserver
  tasks:
    - name: copy war to tomcat
      become: yes
      copy:
        src: ./helloworld.war
        dest: /opt/tomcat8/webapps
        mode: 0755
        group: tomcat
        owner: tomcat
