---
- hosts: loadbalancer
  tasks:
    - name: install nginx
      become: yes
      apt: name=nginx state=latest
    - name: start nginx
      become: yes
      service:
          name: nginx
          state: started
